---
version: "3"
networks:
  default:
    external:
      name: bridge

services:
  yamllint:
    image: monemihir/yamllint:1.29.0
    build:
      context: ./yamllint
      args:
        YAMLLINT_VERSION: "1.29.0"

  awscli:
    image: monemihir/awscli:1.27.62
    build:
      context: ./awscli
      args:
        AWSCLI_VERSION: "1.27.62"
        S3CMD_VERSION: "2.3.0"

  boto3:
    image: monemihir/boto3:1.26.62
    build:
      context: ./boto3
      args:
        BOTO3_VERSION: "1.26.62"

  packer-ansible:
    image: monemihir/packer-ansible:latest
    build:
      context: ./packer-ansible
      args:
        PACKER_VERSION: "1.8.0"
